[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install --only=production']

[phases.build] 
cmds = ['echo "Build ready"']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PORT = '3000'