[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install --only=production', 'cd packages/orchestrator && npm install --only=production']

[phases.build] 
cmds = ['echo "Build completed"']

[start]
cmd = 'cd packages/orchestrator && node src/index.js'

[variables]
NODE_ENV = 'production'
PORT = '3000'