[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'cd packages/orchestrator',
  'npm ci'
]

[phases.build]
cmds = [
  'cd packages/orchestrator',
  'npm run build'
]

[start]
cmd = 'cd packages/orchestrator && npm start'